### ISSUE TITLE
uproot4.recreate does not exist

### ISSUE THREAD

**Issue by VukanJ** [scikit-hep/uproot4#568] opened 2022-03-01 23:13 UTC
Dear uproot developers,
In my very naive understanding, uproot4 (="uproot" nowadays) is supposed to be a rewrite of uproot3 and the feature sets between 3 and 4 do not necessarily match. Should the feature sets of uproot4 and uproot (The library you get via `pip install uproot`) not be identical? I noticed, that the version numbers differ (ok) and that there is no `recreate` method in uproot4, but it exists in uproot and uproot3. Writing is supported in uproot4 since recently, right?
My guess is that this is just a bug that went unnoticed, because no one actually explicitly installs "uproot4" except me ^^ am I wrong?
Thanks!

```
In [8]: import uproot

In [9]: import uproot3

In [10]: import uproot4

In [11]: uproot.__version__
Out[11]: '4.2.0'

In [12]: uproot3.__version__
Out[12]: '3.14.4'

In [13]: uproot4.__version__
Out[13]: '0.1.2'

In [14]: uproot.recreate
Out[14]: <function uproot.writing.writable.recreate(file_path, **options)>

In [15]: uproot3.recreate
Out[15]: uproot3.write.TFile.TFileRecreate

In [16]: uproot4.recreate
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [16], in <module>
----> 1 uproot4.recreate

AttributeError: module 'uproot4' has no attribute 'recreate'
```

**Comment by jpivarski** [comment] 2022-03-01 23:48
That's weird.

Since Dec 5, 2020, the `uproot4` package has been a single-file package whose contents are created by the installation process:

https://github.com/scikit-hep/uproot4/blob/916085ae24c382404254756c86afe760acdece56/build-uproot4.sh#L10-L16

That is, `uproot4` consists entirely of `from uproot import *`. As a package, `uproot4` requires `uproot>=4.0.0`, so it really is a pass-through of whatever's in `uproot`. The package exists as a shim in case anybody got used to

```python
import uproot4
```

and they don't want to change that one line to

```python
import uproot as uproot4
```

For the record, name-changing was a terrible idea. Never do it. It has consequences that don't go away.

Also, you're correct: Uproot 4.x is a new package with a completely new implementation and mostly the same interface as Uproot 3.x. It's a lot more maintainable and has a superset of Uproot 3.x's capabilities. Because of the deep changes, Uproots 3 and 4 coexisted (in the sense that you could import both in the same Python session), so that users could gradually transition, and particularly because it took so long to finish adding file-writing support to Uproot 4.

But if you're ever thinking of doing this, provide one package as a subpackage of the other, as `awkward._v2` is a trial run of version 2 inside `awkward` (and `ROOT::Experimental` is ROOT 7 inside ROOT 6). The package renaming was a terrible idea.

I don't know what to do about this `uproot4` shim not seeing all of `uproot`'s symbols (including its version). Is it really needed for something?

**Comment by VukanJ** [comment] 2022-03-02 00:11
Thank you for this answer, this is reassuring. I don't really need "uproot4" explicitly I guess, "uproot" should be just fine (as long as ">=4" is specified in requirements.txt). In some scripts I am using both versions explicitly (I have not yet figured out how to replicate uproot3's `flatten=True` option of `tree.arrays()` in uproot4, but I admit that I have not read all the docs yet), this is why I installed uproot4 for naming symmetry reasons :)

**Comment by jpivarski** [comment] 2022-05-11 21:09
I'll be closing this because I can't reproduce it. I created a new virtual machine (to be sure that it doesn't have any Python on it), and ran

```
ubuntu@ip-172-31-20-20:~$ pip install uproot4
Defaulting to user installation because normal site-packages is not writeable
Collecting uproot4
  Downloading uproot4-4.0.0-py3-none-any.whl (6.2 kB)
Collecting uproot>=4.0.0
  Downloading uproot-4.2.2-py2.py3-none-any.whl (298 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.4/298.4 KB 12.2 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.22.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 27.6 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from uproot>=4.0.0->uproot4) (59.6.0)
Installing collected packages: numpy, uproot, uproot4
  WARNING: The scripts f2py, f2py3 and f2py3.10 are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.22.3 uproot-4.2.2 uproot4-4.0.0
ubuntu@ip-172-31-20-20:~$ python
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uproot4
>>> uproot4.recreate
<function recreate at 0x7f4668456560>
```

which is what it's supposed to do. Maybe something got tangled in your installation?

Anyway, the right thing to do nowadays is to install the `uproot` package directly. (Which will smoothly transition over to being version 5 later this year, without any name-change mess, just an ordinary version update.)

**Closed by jpivarski** 2022-05-11 21:09 UTC
Labels: bug (unverified)
