### ISSUE TITLE
NotImplementedError: memberwise serialization of AsVector when reading TEfficiency 

### ISSUE THREAD

**Issue by jbeirer** [scikit-hep/uproot4#209] opened 2020-11-30 20:04 UTC
Reading a TEfficiency object from [this](https://github.com/scikit-hep/uproot4/files/5618422/test.root.zip) file using

```python
import uproot4
file = uproot4.open("test.root")
teff = file["TEfficiencyName"]
```
results in the following ```NotImplementedError```:

```python
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-20-a83e57b60271> in <module>
      1 import uproot4
      2 file = uproot4.open("test.root")
----> 3 teff = file["TEfficiencyName"]

~/pyvenv/lib64/python3.6/site-packages/uproot4/reading.py in __getitem__(self, where)
   1977 
   1978         else:
-> 1979             return self.key(where).get()
   1980 
   1981     @property

~/pyvenv/lib64/python3.6/site-packages/uproot4/reading.py in get(self)
   2362 
   2363             try:
-> 2364                 out = cls.read(chunk, cursor, context, self._file, selffile, parent)
   2365 
   2366             except uproot4.deserialization.DeserializationError:

~/pyvenv/lib64/python3.6/site-packages/uproot4/model.py in read(cls, chunk, cursor, context, file, selffile, parent, concrete)
   1141         return cls.postprocess(
   1142             versioned_cls.read(
-> 1143                 chunk, cursor, context, file, selffile, parent, concrete=concrete
   1144             ),
   1145             chunk,

~/pyvenv/lib64/python3.6/site-packages/uproot4/model.py in read(cls, chunk, cursor, context, file, selffile, parent, concrete)
    771         )
    772 
--> 773         self.read_members(chunk, cursor, context, file)
    774 
    775         self.hook_after_read_members(

<dynamic> in read_members(self, chunk, cursor, context, file)

~/pyvenv/lib64/python3.6/site-packages/uproot4/containers.py in read(self, chunk, cursor, context, file, selffile, parent, header)
    749                 """memberwise serialization of {0}
    750 in file {1}""".format(
--> 751                     type(self).__name__, selffile.file_path
    752                 )
    753             )

NotImplementedError: memberwise serialization of AsVector
in file test.root
```

Tested with uproot4 version: ```0.1.2```

**Comment by jpivarski** [comment] 2020-11-30 20:43
Thanks for that. I didn't realize that TEfficiency would have memberwise data in it, but that ties this issue in with #38. Memberwise deserialization will be implemented for `std::vector` first, using this file as a test-driven example.

**Comment by jpivarski** [comment] 2021-02-18 15:00
I'm closing this as a duplicate of #38, which is still a high-priority item. Consolidation makes it easier for me to see what needs to be done.

**Closed by jpivarski** 2021-02-18 15:00 UTC
Labels: bug (unverified), duplicate
