### ISSUE TITLE
Enable autocomplete of loaded objects from root files

### ISSUE THREAD

**Issue by DingXuefeng** [scikit-hep/uproot4#559] opened 2022-02-14 19:44 UTC
Expected behavior:

```python
with uproot.open("input.root") as f:
   obj = f["histogram"]
   obj. # (here pop out list of member and methods, such as to_numpy)
   obj.to_numpy # (shift+tab: show documentation of to_numpy function)
```

Current behavior:
- nothings pops up.

Test environment:
- python3.9 + Jupiter-lab or ipython

**Comment by jpivarski** [comment] 2022-02-14 21:46
Hmm. Those functions have standard docstrings:

```python
>>> import uproot
>>> import skhep_testdata
>>> f = uproot.open(skhep_testdata.data_path("uproot-histograms.root"))
>>> one = f["one"]
>>> one
<TH1F (version 2) at 0x7f53bb2660d0>
>>> help(one.to_numpy)
```

(help fills the screen with my chosen pager).

Let me try JupyterLab. Shift-tab worked for me in JupyterLab. (I didn't know about that feature; thanks!) I have version 3.2.5-2 of JupyterLab...

![image](https://user-images.githubusercontent.com/1852447/153950708-8c414b68-a791-45cc-839a-40939b0053c2.png)

I found [this on StackOverflow](https://stackoverflow.com/q/59008693/1623645).

And I played around with it a bit more. The object needs to be defined in Python before shift-tab can work—how else can JupyterLab internally call `help` on it?—and you can't shift-tab on an object that gets defined in the same cell. Since you haven't evaluated that cell yet, it doesn't exist in Python yet. Given that your code example includes the definition of `obj` in the same block of text where you're trying to get the help, I'm guessing that's what happened here. It's because you arranged the code in a `with` block (a good practice!) that you can't evaluate only part of it. In my example, I put the definition of `one` and the `one.to_numpy` shift-tab in the same cell (without having `one` evaluated from a previous attempt) and saw the same behavior.

Guessing that that's what the problem is, I'm going to close this issue. If I'm wrong, feel free to tell me so (I'll still see messages here).

**Closed by jpivarski** 2022-02-14 21:46 UTC
Labels: feature

**Comment by DingXuefeng** [comment] 2022-02-15 04:27
Thanks for the detailed explanation.

The auto-complete engine either deduce type from static analysis or by looking up in-memory objects. Removing `with` allows the second mechanism and solves the problem.

**Comment by DingXuefeng** [comment] 2022-02-15 04:32
PS: I know this does not sounds reasonable, but in some tests I removed the `with`, and the `one` is indeed in the memory, while I still cannot complete it... by that time I think the auto-complete engine sometimes cannot deduce the type of in-memory object.. Yet I cannot reproduce it now....  

Seems to be a Heisenbug.. :( I dedice to let it go.

**Comment by jpivarski** [comment] 2022-02-15 18:26
Oh, then we can call this the first formal request for Uproot to have static typing. That would be a _major_ project.

Actually, no: even with full static typing, Python + mypy + Jupyter would not be able to figure out that `obj` has type [Histogram](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TH1.Histogram.html) because that depends on values derived from a file.

But there are other places where static typing could help Jupyter discover docstrings without having to evaluate them. Just not this one.

**Comment by DingXuefeng** [comment] 2022-08-03 19:50
Ahh so I see you and hear your talk today! LOL
