### ISSUE TITLE
Internal error while coordinating basket-reads for a branch

### ISSUE THREAD

**Issue by lucaswiens** [scikit-hep/uproot4#54] opened 2020-07-20 15:38 UTC
I think I may have found a bug.
During skimming, I store quantities as std::vector<float> and write those into the root tree. However, when using uproot4 and doing something like
`uproot4.open("Test_1.root")["Events"]["Muon_Pt"].array()`
I get the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/dust/cms/user/wiens/anaconda3/envs/hepML/lib/python3.8/site-packages/uproot4/behaviors/TBranch.py", line 1548, in array
    _ranges_or_baskets_to_arrays(
  File "/nfs/dust/cms/user/wiens/anaconda3/envs/hepML/lib/python3.8/site-packages/uproot4/behaviors/TBranch.py", line 509, in _ranges_or_baskets_to_arrays
    uproot4.source.futures.delayed_raise(*obj)
  File "/nfs/dust/cms/user/wiens/anaconda3/envs/hepML/lib/python3.8/site-packages/uproot4/source/futures.py", line 33, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/nfs/dust/cms/user/wiens/anaconda3/envs/hepML/lib/python3.8/site-packages/uproot4/behaviors/TBranch.py", line 451, in basket_to_array
    interpretation = branchid_interpretation[id(branch)]
KeyError: 139865518582800
`
Doing the exact same thing but using uproot (i.e. uproot3) instead it just works.

**Comment by jpivarski** [comment] 2020-07-20 15:40
Can you provide an example of the file, publicly (here) or privately (by email)?

**Comment by lucaswiens** [comment] 2020-07-20 15:47
I have uploaded the file I used to my cernbox
https://cernbox.cern.ch/index.php/s/Upu7X3T8l7zdk8e

**Comment by jpivarski** [comment] 2020-07-20 15:53
Darn; I can't reproduce it. Can you tell me more about your environment? Like, operating system, what kind of file system the file is on, Python version, etc?

**Comment by lucaswiens** [comment] 2020-07-20 15:59
Hmm.. That is interesting. I use SL7, and the file is on the DUST system at DESY (I don't know if you are familiar with it but I am also not sure what kind of answer you want here tbh).
The python version is Python 3.8.3. I setup a conda environment and installed uproot4 using pip.

**Comment by jpivarski** [comment] 2020-07-20 16:10
I might have just found it. I switched from using `id(branch)` everywhere as a unique identifier (which should be okay as long as the branch that is being read doesn't get deleted while it's being read) to using `branch.cache_key` as a unique identifier (recently added, as part of caching). After doing so, I managed it get it to raise an error on the line you pointed out (i.e. something's wrong), though not with your file. Despite how transitory this seems, it's probably the same error.

**Comment by jpivarski** [comment] 2020-07-20 16:19
Actually, no, it was just the way the test was written. (The test had been hard-coded to `id(branch)`; updating it to `branch.cache_key` fixed it.)

I haven't been able to reproduce it. The following always works for me:

```python
>>> import uproot4
>>> uproot4.open("uproot4-issue-54.root")["Events"]["Muon_Pt"].array()
<Array [[], [], [], [], ... [113], [], []] type='561602 * var * float32'>
```

I'll look around for anything that might look like a race condition. Meanwhile, maybe you could try PR #55 to see if it fixes the problem for you? Your problem is a missing dict key; now the dict keys are strings associated with the file UUID, TTree path, TBranch name and location in the TTree. The `id(branch)` values are actually pointers, so this is probably safer, or at least might give better debugging information.

**Comment by jpivarski** [comment] 2020-07-20 16:22
I also see no problems when I use the `FileSource`, which would be the fallback if your filesystem doesn't support memory-mapping.

```python
uproot4.open("uproot4-issue-54.root", file_handler=uproot4.source.file.FileSource)
```

**Comment by lucaswiens** [comment] 2020-07-20 16:30
It works now. Thanks for the very quick help.

**Comment by jpivarski** [comment] 2020-07-20 16:36
Okay, then I'll keep it as `branch.cache_key` and always be suspicious of using `id(...)` for identifiers in the future.

I don't know what _exactly_ went wrong, but perhaps the `branch` went out of scope and came back with a different `id`. At least the `cache_key` will always be the same (even between processes, not that it matters for a short-lived dict).

Also, there was no chance of a race condition: the dict is filled with a single item long before the machinery to start filling arrays is even invoked.

**Closed by jpivarski** 2020-07-20 16:36 UTC
