### ISSUE TITLE
XRootD vector_read leaks memory

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/uproot4#294] opened 2021-03-04 20:37 UTC
XRootD vector_read leaks memory and should not be the default until the issue is fixed upstream.
Here is a reproducible example that demonstrates the problem:

```python
import uproot
import threading
from queue import Queue
import psutil
import time
import tqdm
import gc


notifications = Queue()

def worker():
    # just eat the chunks as they come in
    while True:
        notifications.get()
        notifications.task_done()


usage = []
def collect_usage():
    chunktype = uproot.source.chunk.Chunk
    usage.append({
        "dt": time.time() - tstart,
        "rss": process.memory_info().rss,
        "nchunks": sum(isinstance(o, chunktype) for o in gc.get_objects()),
    })

threading.Thread(target=worker, daemon=True).start()
process = psutil.Process()
step = 1024 * 32  # a typical basket size
step2 = 10  # like number of baskets per chunk

fn = "root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root"
with uproot.source.xrootd.XRootDSource(fn, **uproot.open.defaults) as source:
    maxbytes = source.num_bytes  # how much memory would you like to use? :)
    ranges = [(start, start + step) for start in range(0, maxbytes, step)]

    usage = []
    tstart = time.time()
    for i in tqdm.trange(0, len(ranges), step2):
        subranges = ranges[i:i + step2]
        chunks = source.chunks(subranges, notifications)
        notifications.join()
        del chunks  # this *should* be the only reference to the data
        gc.collect()  # the chunks seem to have cycles
        collect_usage()

collect_usage()
import pandas
usage = pandas.DataFrame(usage).set_index("dt")
```

If I then plot the data:
```python
from matplotlib.ticker import EngFormatter

ax = usage.plot(secondary_y="nchunks")
ax.yaxis.set_major_formatter(EngFormatter(unit='b'))
ax.set_title(f"Reading {maxbytes/1e9:.1f}Gb from a file")
```
I get:
![image](https://user-images.githubusercontent.com/6587412/110027028-14a42480-7cf7-11eb-8a0f-dd6c8bf7325d.png)

PS I reported this behavior a long time ago https://github.com/scikit-hep/uproot4/issues/2#issuecomment-629300538

**Comment by jpivarski** [comment] 2021-03-04 20:40
Please do make it non-default. I'll release a new version of Uproot when that's merged into main.

Thanks!

**Comment by nsmith-** [comment] 2021-03-04 20:40
More python objects that are not being held:

```python
import numpy
sum(isinstance(o, numpy.ndarray) for o in gc.get_objects())
```
is 2

```python
import XRootD
sum(isinstance(o, XRootD.client.responses.ChunkInfo) for o in gc.get_objects())
```
is 0

**Comment by nsmith-** [comment] 2021-03-04 20:45
FYI @chrisburr may be interested

**Closed** 2021-03-04 20:58 UTC
Labels: bug (unverified)

**Comment by nsmith-** [comment] 2021-03-04 22:18
The example works for MultithreadedXRootDSource but the `notifications.join()` was not sufficient synchronization to wait for the futures somehow. I rewrote it to block properly and indeed the multithreaded source memory does not grow.
That said, there is still a bit of an issue in the delayed gc on the Chunk objects. If I remove `gc.collect()` I end up with something like this:
![image](https://user-images.githubusercontent.com/6587412/110038359-42906580-7d05-11eb-97a7-c762bc8035e0.png)

Which is a bit unfortunate because in principle none of this data needs to be around any longer than handing the chunk to whatever decompression executor the basket has.

**Comment by ryuwd** [comment] 2021-03-04 22:28
Is it sufficient to set `MultithreadedXRootDSource` as the default xrootd source to avoid the leak, or does something else need to be done (i.e. adding a `gc.collect()` call somewhere?)

**Comment by nsmith-** [comment] 2021-03-04 22:53
@ryuwd yeah that avoids the leak described here. And that is what was done in PR #295.

**Comment by chrisburr** [comment] 2021-03-05 06:48
It looks like this has already been reported https://github.com/xrootd/xrootd/issues/1400 and the cause the leak has been found. I'll try to find time to make a PR if nobody beats me to it.
