### ISSUE TITLE
Interpretation issue in extraction of vector of user-defined class objects

### ISSUE THREAD

**Issue by dano0014** [scikit-hep/uproot4#288] opened 2021-03-02 01:02 UTC
Our ROOT structure is as follows. Within the ROOT file there are a few TTrees, but the only one that is relevant is the Event TTree. Within that Event TTree there is a group that shows up with the typename "std::vector<ChannelData> channels" as each event has some # of channels. Each channel class has a member, "pulse". The pulse member shows up with the typename "std::vector<Pulse> pulses". I am looking for the information in the Pulse group, but it is showing up as a pointer (I think). The interpretation says "AsObjects(AsArray(True,False,None" but that is all that I can see. In ROOT the code would look like "event->channels[0].pulses[0].nph" and I would like to know how to convert that to python. I have also sent the Jupyter Notebook so you can better understand what I mean. Thank you for any help you can provide.

Also on the PyHEP-newcomers chat on Gitter, Mr. Pivarski had suggested writing "pulse.array()" which crashes my computer and "puls.array(library-"np")" which returns a "memberwise serialization of AsArray" NotImplementedError.

https://files.gitter.im/5c939a19d73408ce4fbb5e66/R1CK/uproot_problem.ipynb

https://northwestern.box.com/s/4x1w6ym8wsion6lgx49xwfuhkh7gvcdk
that is the link to the full data file (warning, it is pretty big, 3.5gb).

**Comment by jpivarski** [comment] 2021-03-02 13:41
Actually, if it says `NotImplementedError("memberwise serialization of AsArray")`, that's a duplicate of issue #38. I need to investigate and add deserialization code for ROOT's "memberwise" option—it simply doesn't exist at the moment.

Although the `"AsObjects(AsArray(True,False,None"` string also looks wrong: an Interpretation ought to return its string representation but is just returning (the string) `"None"` for some reason. I'll look at that, too.

**Comment by jpivarski** [comment] 2021-05-18 09:50
Sorry that I lost track of this one!

I've verified that you get the "memberwise serialization" error, but that is a duplicate of #38.

The other thing I was worried about, the interpretation name with `"None"` in it, is apparently gone:

```python
>>> uproot.open("uproot-issue-288.root:Events/event/channels/channels.pulses").interpretation
AsObjects(AsArray(True, False, AsVector(False, Model_Pulse)))
```

**Closed** 2021-05-18 09:50 UTC
Labels: duplicate
