### ISSUE TITLE
Can't access some branches in MiniAOD

### ISSUE THREAD

**Issue by yhs07128** [scikit-hep/uproot4#308] opened 2021-03-19 12:37 UTC
I'm trying to read some branch

`patMETs_slimmedMETs__PAT.obj.m_state.p4Polar_.Pt()`

in MiniAOD, but uproot doesn't recognize it as a branch. If I do

`event['patMETs_slimmedMETs__PAT.'].show()`

it shows that the branch is not interpreted properly.

name                 | typename                 | interpretation    
---------------------+--------------------------+-------------------------------
patMETs_slimmedMETs_ | edm::Wrapper<vector<pat: | AsGroup(<TBranchElement 'patMEpatMETs_slimmedME... | bool                     | AsDtype('bool')
patMETs_slimmedME... | unknown                  | <UnknownInterpretation 'non...

There are multiple other branches with the same problem, but I'm not sure what's causing it.

I'm using the latest version (4.0.6). I can't find a public MiniAOD at the moment, but I think any file will reproduce the issue.

**Comment by jpivarski** [comment] 2021-03-19 14:01
The reason is that not all data types have been reverse-engineered; when a data type is not recognized, it is presented as "unknown."

I found a random MiniAOD file (`Run2016G/SingleMuon/MINIAOD/23Sep2016-v1/90000/1C603D88-C597-E611-A0BE-008CFAF2931E.root`) and tried it out. These branches don't have "`PAT`" in their names, but "`RECO`", though I suspect that they're the same types of objects because CMSSW's naming convention puts the type first, then collection name, etc. The branch I'm looking in is

   * `"patMETs_slimmedMETs__RECO./patMETs_slimmedMETs__RECO.obj/patMETs_slimmedMETs__RECO.obj.m_state.p4Polar_.fCoordinates.fPt"`

and I find that the branch is readable:

```python
>>> t["patMETs_slimmedMETs__RECO./patMETs_slimmedMETs__RECO.obj/patMETs_slimmedMETs__RECO.obj.m_state.p4Polar_.fCoordinates.fPt"].array()
<Array [[36.6], [28.6], ... [28.1], [67.7]] type='97194 * var * float64'>
```

Moreover, this whole group of branches (everything under the same parent branch) has an interpretation:

```
>>> t["patMETs_slimmedMETs__RECO./patMETs_slimmedMETs__RECO.obj"].show()
name                 | typename                 | interpretation                
---------------------+--------------------------+-------------------------------
patMETs_slimmedMETs_ | (group of patMETs_slimme | AsGroup(<TBranchElement 'patME
patMETs_slimmedME... | float[]                  | AsJagged(AsDtype('>f4', 'fl...
patMETs_slimmedME... | float[]                  | AsJagged(AsDtype('>f4', 'fl...
patMETs_slimmedME... | float[]                  | AsJagged(AsDtype('>f4', 'fl...
patMETs_slimmedME... | float[]                  | AsJagged(AsDtype('>f4', 'fl...
patMETs_slimmedME... | float[]                  | AsJagged(AsDtype('>f4', 'fl...
patMETs_slimmedME... | float[]                  | AsJagged(AsDtype('>f4', 'fl...
patMETs_slimmedME... | float[]                  | AsJagged(AsDtype('>f4', 'fl...
patMETs_slimmedME... | int32_t[]                | AsJagged(AsDtype('>i4'))
patMETs_slimmedME... | int32_t[]                | AsJagged(AsDtype('>i4'))
patMETs_slimmedME... | int32_t[]                | AsJagged(AsDtype('>i4'))
patMETs_slimmedME... | double[]                 | AsJagged(AsDtype('>f8'))
patMETs_slimmedME... | double[]                 | AsJagged(AsDtype('>f8'))
patMETs_slimmedME... | double[]                 | AsJagged(AsDtype('>f8'))
patMETs_slimmedME... | double[]                 | AsJagged(AsDtype('>f8'))
patMETs_slimmedME... | double[]                 | AsJagged(AsDtype('>f8'))
patMETs_slimmedME... | double[]                 | AsJagged(AsDtype('>f8'))
patMETs_slimmedME... | std::vector<CorrMETDa... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | edm::RefCore*            | AsJagged(AsStridedObjects(M...
patMETs_slimmedME... | uint64_t[]               | AsJagged(AsDtype('>u8'))
patMETs_slimmedME... | std::vector<pat::Trig... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<pat::Look... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<std::stri... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<edm::Ref<... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<reco::Gen... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<std::stri... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<edm::PtrV... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<std::stri... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<pat::User... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<std::stri... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<float>*      | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<std::stri... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<int32_t>*    | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<std::stri... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<edm::Ptr<... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<pat::Cand... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<std::stri... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<reco::Gen... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<SpecificC... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<SpecificP... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | double[]                 | AsJagged(AsDtype('>f8'))
patMETs_slimmedME... | std::vector<pat::MET:... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<pat::MET:... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<pat::MET:... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<pat::MET:... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | std::vector<pat::MET:... | AsObjects(AsArray(True, Fal...
patMETs_slimmedME... | uint16_t[]               | AsJagged(AsDtype('>u2'))
patMETs_slimmedME... | uint16_t[]               | AsJagged(AsDtype('>u2'))
patMETs_slimmedME... | uint16_t[]               | AsJagged(AsDtype('>u2'))
```

So maybe you have an old version of Uproot? It could be that the type you want wasn't interpreted at the time your Uproot version was released, but now it's done. (It's a continual process...)

Oh, and one other thing: a name ending with parentheses, such as "`patMETs_slimmedMETs__PAT.obj.m_state.p4Polar_.Pt()`", is not a branch name but a C++ method executed on the branch. (The C++ method is "`Pt`" and the class instance is `p4Polar_` in this case.) C++ methods do not exist in the ROOT files; they are a part of CMSSW that aren't available if you take the file out of the ROOT+CMSSW world. If the C++ method only extracts the `fCoordinates.fPt` (member data) and returns it, then you just have to do that manually instead. If it applied some sort of corrections, then you have to reproduce those corrections—if they were expressed as code in the CMSSW codebase and you're not using the CMSSW codebase, then you can't get them except by looking up that code and reproducing it.

**Comment by yhs07128** [comment] 2021-03-19 14:25
Hmm... okay. I also initially thought it was an issue with the file because most of the branches were loading fine. But there's no problem accessing them with ROOT.

I guess I can upload one here since it's a MC.

[output_1.txt](https://github.com/scikit-hep/uproot4/files/6171768/output_1.txt) 

It will be great if you can take a quick look. Thanks!

**Comment by jpivarski** [comment] 2021-03-19 14:37
For the main intention of getting the `pt`, there's

```python
>>> t["patJets_slimmedJets__PAT./patJets_slimmedJets__PAT.obj/patJets_slimmedJets__PAT.obj.m_state.p4Polar_.fCoordinates.fPt"].array()
<Array [[71.6, 53.3, 49.6, ... 10.8, 10.8]] type='250 * var * float64'>
```

although I do see a few unknown interpretations in this file. I'm looking into what those are now.

**Comment by jpivarski** [comment] 2021-03-19 15:07
The unknown interpretations are all "`product_`" and "`keys_`", which are not physics data anyway. (They have something to do with the CMSSW infrastructure.)

```
patJets_slimmedJets__PAT.obj.genJetRef_.refVector_.product_                      | unknown
patJets_slimmedJets__PAT.obj.genJetRef_.refVector_.keys_                         | unknown
patJets_slimmedJets__PAT.obj.genJetFwdRef_.ref_.product_                         | unknown
patJets_slimmedJets__PAT.obj.genJetFwdRef_.backRef_.product_                     | unknown
patJets_slimmedJets__PAT.obj.jetFlavourInfo_.m_bHadrons.refVector_.product_      | unknown
patJets_slimmedJets__PAT.obj.jetFlavourInfo_.m_bHadrons.refVector_.keys_         | unknown
patJets_slimmedJets__PAT.obj.jetFlavourInfo_.m_cHadrons.refVector_.product_      | unknown
patJets_slimmedJets__PAT.obj.jetFlavourInfo_.m_cHadrons.refVector_.keys_         | unknown
patJets_slimmedJets__PAT.obj.jetFlavourInfo_.m_partons.refVector_.product_       | unknown
patJets_slimmedJets__PAT.obj.jetFlavourInfo_.m_partons.refVector_.keys_          | unknown
patJets_slimmedJets__PAT.obj.jetFlavourInfo_.m_leptons.refVector_.product_       | unknown
patJets_slimmedJets__PAT.obj.jetFlavourInfo_.m_leptons.refVector_.keys_          | unknown
```

I'm going to mark this as "won't fix" because you can get access to the physics data. Just be sure to check to find out whether the `Pt()` (method call) that you want is applying important corrections that aren't present in the `fPt` (member data).

**Closed by jpivarski** 2021-03-19 15:07 UTC
Labels: bug (unverified)

**Comment by yhs07128** [comment] 2021-03-19 15:18
But you can see there's an entire branch under `patMETs_slimmedMETs__PAT.` with TBrowser, and it contains different pt from the branch you mentioned because it stores missing-eT(MET) of events. The () was a typo because I copied the path from somewhere else. Sorry if that caused some confusion.

**Comment by yhs07128** [comment] 2021-03-19 15:59
![jetPt](https://user-images.githubusercontent.com/64108850/111808581-7ed3e080-8917-11eb-9001-9b8ea782f6a0.png)
![met](https://user-images.githubusercontent.com/64108850/111808585-80050d80-8917-11eb-998c-505094a91325.png)

**Comment by jpivarski** [comment] 2021-03-19 16:00
Ah, somewhere between the first file and the second I swapped "MET" for "Jet". (I know what it was! I used the "nearest branch name" KeyError to pick what I thought was a misspelling, without reading it carefully.)

The `patMETs_slimmedMETs__PAT.obj` branch is uninterpreted and it contains no subbranches—it must be "unsplit."

```
>>> t["patMETs_slimmedMETs__PAT.obj"].show()
name                 | typename                 | interpretation                
---------------------+--------------------------+-------------------------------
patMETs_slimmedMETs_ | unknown                  | <UnknownInterpretation 'none o
>>> t["patMETs_slimmedMETs__PAT.obj"].keys()
[]
>>> t["patMETs_slimmedMETs__PAT.obj"].interpretation
<UnknownInterpretation 'none of the rules matched'>
```

The TBrowser shows "split" and "unsplit" branches the same way, but they're very different serializations. In order to read an unsplit branch, you need to be able to read every field because they're contiguous (i.e. you can't get to the Nth field if you haven't successfully read the N‒1th field), whereas split branches can each be read independently. Not only does that mean that Uproot's support for split data is better, because if you want floating-point `pt` values, you only need to be able to read floating-point numbers, but even if it is possible to read an unsplit branch, the corresponding split branch will always be faster.

(It would be faster for two reasons: first, because if you only one `pt` and a few other fields, you don't have to read and decompress unwanted fields, which affects both Uproot and ROOT. Second, because complex unsplit types have to be deserialized with a "for" loop, which is implemented in Python, rather than NumPy, in Uproot. That latter issue is going to be fixed with AwkwardForth, but the first issue will always be there.)

**Comment by jpivarski** [comment] 2021-03-19 16:01
Our comments cross in the mail.

**Comment by yhs07128** [comment] 2021-03-19 16:08
Ah, that makes sense. So you mean the unsplit branches aren't supported?

**Comment by jpivarski** [comment] 2021-03-19 16:19
"Fewer" unsplit branches are supported. Some do work because all fields are interpretable and of course we're not going to prevent it from being read. But then, I always give the performance-related warning about requests to implement unsplit types because after all that work, it won't be very fast, and that might be a show-stopper for actually using it. Splitting is preferable in most end-user applications, and that's why ROOT's new RNTuple is 100% split by design.

**Comment by yhs07128** [comment] 2021-03-19 16:41
Well then guess I'll have to use ROOT. With that said, I'm much more comfortable in the python environment and uproot has been awesome so far. I think that numpy+uproot approach will become mainstream in the near future.

Thanks for the quick response!

**Comment by jpivarski** [comment] 2021-03-19 17:10
Maybe try RDataFrame in Python. We hope to integrate that with Awkward Array (https://github.com/scikit-hep/awkward-1.0/issues/588), which would provide more avenues for integration with the Python ecosystem.
